logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  datasource:
    url: jdbc:mysql://blobus.mysql.database.azure.com:3306/database_blobus?serverTimezone=UTC
    username: apiexterneblobus
    password: Blobusteam2023!
    jpa.show-sql: true
    hibernate:
      ddl-auto: update
    jpa.database-platform: org.hibernate.dialect.MySQL5Dialect



